/**
 * Static reference data for the seed.
 *
 * Kept apart from the seeding logic so the catalogue, policy matrix and company
 * list can be reviewed as data rather than read out of procedural code.
 */

export const PRODUCT_CATALOGUE = [
  // --- platform and editions ---------------------------------------------
  {
    sku: 'SPOT-PLAT-CORE',
    name: 'SpotOn Platform — Core',
    family: 'Platform',
    type: 'edition',
    billingModel: 'per_user',
    unitOfMeasure: 'seat',
    isRecurring: true,
    editionRank: 1,
    revenueCategory: 'subscription',
    listUnitCents: 90_000,
    maxDiscountBps: 1500,
    entitlementTemplate: [{ featureKey: 'core_platform' }, { featureKey: 'api_access', limitValue: 100_000 }],
    description: 'Core revenue platform: accounts, contacts, pipeline and reporting.',
  },
  {
    sku: 'SPOT-PLAT-PRO',
    name: 'SpotOn Platform — Professional',
    family: 'Platform',
    type: 'edition',
    billingModel: 'per_user',
    unitOfMeasure: 'seat',
    isRecurring: true,
    editionRank: 2,
    revenueCategory: 'subscription',
    listUnitCents: 132_000,
    maxDiscountBps: 2000,
    entitlementTemplate: [
      { featureKey: 'core_platform' },
      { featureKey: 'forecasting' },
      { featureKey: 'api_access', limitValue: 500_000 },
      { featureKey: 'support', supportLevel: 'enterprise' },
    ],
    description: 'Adds forecasting, approvals and workflow automation.',
  },
  {
    sku: 'SPOT-PLAT-ENT',
    name: 'SpotOn Platform — Enterprise',
    family: 'Platform',
    type: 'edition',
    billingModel: 'per_user',
    unitOfMeasure: 'seat',
    isRecurring: true,
    editionRank: 3,
    revenueCategory: 'subscription',
    listUnitCents: 186_000,
    maxDiscountBps: 2500,
    entitlementTemplate: [
      { featureKey: 'core_platform' },
      { featureKey: 'forecasting' },
      { featureKey: 'territory_management' },
      { featureKey: 'field_level_security' },
      { featureKey: 'api_access', limitValue: 5_000_000 },
      { featureKey: 'support', supportLevel: 'premier' },
    ],
    description: 'Full governance, territory management and unlimited automation.',
  },

  // --- modules -------------------------------------------------------------
  {
    sku: 'SPOT-MOD-RENEW',
    name: 'Renewal Management',
    family: 'Renewals',
    type: 'module',
    billingModel: 'flat_fee',
    unitOfMeasure: 'tenant',
    isRecurring: true,
    revenueCategory: 'subscription',
    listUnitCents: 2_400_000,
    maxDiscountBps: 2000,
    entitlementTemplate: [{ featureKey: 'renewal_desk' }],
    description: 'Renewal desk, notice tracking, uplift and save plays.',
  },
  {
    sku: 'SPOT-MOD-SUBS',
    name: 'Subscription Management',
    family: 'Subscriptions',
    type: 'module',
    billingModel: 'flat_fee',
    unitOfMeasure: 'tenant',
    isRecurring: true,
    revenueCategory: 'subscription',
    listUnitCents: 3_600_000,
    maxDiscountBps: 2000,
    entitlementTemplate: [{ featureKey: 'subscription_engine' }, { featureKey: 'co_termination' }],
    description: 'Amendments, co-termination, proration and the ARR ledger.',
  },
  {
    sku: 'SPOT-MOD-CS',
    name: 'Customer Success Cloud',
    family: 'Customer Success',
    type: 'module',
    billingModel: 'per_user',
    unitOfMeasure: 'seat',
    isRecurring: true,
    revenueCategory: 'subscription',
    listUnitCents: 66_000,
    maxDiscountBps: 2500,
    entitlementTemplate: [{ featureKey: 'success_plans' }, { featureKey: 'health_scoring' }],
    description: 'Success plans, health scoring, risks and save plays.',
  },
  {
    sku: 'SPOT-MOD-SERVICE',
    name: 'Service Desk',
    family: 'Service',
    type: 'module',
    billingModel: 'per_user',
    unitOfMeasure: 'seat',
    isRecurring: true,
    revenueCategory: 'subscription',
    listUnitCents: 54_000,
    maxDiscountBps: 2500,
    entitlementTemplate: [{ featureKey: 'service_desk' }, { featureKey: 'sla_management' }],
    description: 'Ticketing with entitlement-driven SLAs and escalation.',
  },
  {
    sku: 'SPOT-MOD-PARTNER',
    name: 'Partner Cloud',
    family: 'Partners',
    type: 'module',
    billingModel: 'flat_fee',
    unitOfMeasure: 'tenant',
    isRecurring: true,
    revenueCategory: 'subscription',
    listUnitCents: 1_800_000,
    maxDiscountBps: 3000,
    entitlementTemplate: [{ featureKey: 'deal_registration' }],
    description: 'Deal registration, partner tiers and channel attribution.',
  },

  // --- add-ons -------------------------------------------------------------
  {
    sku: 'SPOT-ADD-AI',
    name: 'Revenue Intelligence',
    family: 'Intelligence',
    type: 'add_on',
    billingModel: 'per_user',
    unitOfMeasure: 'seat',
    isRecurring: true,
    revenueCategory: 'subscription',
    listUnitCents: 42_000,
    maxDiscountBps: 2000,
    entitlementTemplate: [{ featureKey: 'deal_inspection' }, { featureKey: 'next_best_action' }],
    description: 'Deal inspection, risk signals and next-best-action.',
  },
  {
    sku: 'SPOT-ADD-MCP',
    name: 'Claude MCP Connector',
    family: 'Intelligence',
    type: 'add_on',
    billingModel: 'flat_fee',
    unitOfMeasure: 'tenant',
    isRecurring: true,
    revenueCategory: 'subscription',
    listUnitCents: 900_000,
    maxDiscountBps: 1500,
    entitlementTemplate: [{ featureKey: 'mcp_server' }],
    description: 'Model Context Protocol server for Claude, with scoped write access.',
  },
  {
    sku: 'SPOT-ADD-SANDBOX',
    name: 'Sandbox Environment',
    family: 'Platform',
    type: 'add_on',
    billingModel: 'flat_fee',
    unitOfMeasure: 'tenant',
    isRecurring: true,
    revenueCategory: 'subscription',
    listUnitCents: 1_200_000,
    maxDiscountBps: 3000,
    entitlementTemplate: [{ featureKey: 'sandbox', limitValue: 3 }],
    description: 'Full-copy sandboxes for testing and release management.',
  },

  // --- usage ---------------------------------------------------------------
  {
    sku: 'SPOT-USG-API',
    name: 'API Calls',
    family: 'Platform',
    type: 'usage',
    billingModel: 'usage_based',
    unitOfMeasure: 'api_call',
    isRecurring: true,
    revenueCategory: 'usage',
    listUnitCents: 12,
    maxDiscountBps: 1500,
    includedVolume: 1_000_000,
    overageUnitCents: 18,
    entitlementTemplate: [{ featureKey: 'api_calls', limitValue: 1_000_000 }],
    description: 'Metered API consumption above the included allowance.',
  },
  {
    sku: 'SPOT-USG-ENRICH',
    name: 'Data Enrichment Credits',
    family: 'Intelligence',
    type: 'usage',
    billingModel: 'usage_based',
    unitOfMeasure: 'transaction',
    isRecurring: true,
    revenueCategory: 'usage',
    listUnitCents: 45,
    maxDiscountBps: 2000,
    includedVolume: 50_000,
    overageUnitCents: 65,
    entitlementTemplate: [{ featureKey: 'enrichment', limitValue: 50_000 }],
    description: 'Firmographic and contact enrichment credits.',
  },

  // --- services and support ------------------------------------------------
  {
    sku: 'SPOT-SVC-IMPL',
    name: 'Implementation Services',
    family: 'Services',
    type: 'service',
    billingModel: 'one_time',
    unitOfMeasure: 'engagement',
    isRecurring: false,
    revenueCategory: 'services',
    listUnitCents: 4_500_000,
    maxDiscountBps: 4000,
    description: 'Guided implementation, data migration and integration build.',
  },
  {
    sku: 'SPOT-SVC-TRAIN',
    name: 'Administrator Training',
    family: 'Services',
    type: 'service',
    billingModel: 'one_time',
    unitOfMeasure: 'engagement',
    isRecurring: false,
    revenueCategory: 'services',
    listUnitCents: 950_000,
    maxDiscountBps: 5000,
    description: 'Four-day administrator certification programme.',
  },
  {
    sku: 'SPOT-SUP-PREM',
    name: 'Premier Support',
    family: 'Support',
    type: 'support',
    billingModel: 'flat_fee',
    unitOfMeasure: 'tenant',
    isRecurring: true,
    revenueCategory: 'support',
    listUnitCents: 3_000_000,
    maxDiscountBps: 1500,
    entitlementTemplate: [{ featureKey: 'support', supportLevel: 'premier', firstResponseSlaMinutes: 15 }],
    description: '15-minute severity-1 response, named technical account manager.',
  },
] as const;

/**
 * The discount approval matrix. Thresholds escalate, and non-standard paper always
 * draws deal desk regardless of price.
 */
export const DISCOUNT_POLICY_MATRIX = [
  {
    name: 'Sales Manager approval',
    sequence: 1,
    thresholdBps: 1000,
    approverRoleKey: 'sales_manager',
    triggersOnNonStandardTerms: false,
    slaHours: 24,
    escalateToRoleKey: 'vp_sales',
  },
  {
    name: 'VP Sales approval',
    sequence: 2,
    thresholdBps: 2000,
    approverRoleKey: 'vp_sales',
    triggersOnNonStandardTerms: false,
    slaHours: 24,
    escalateToRoleKey: 'cro',
  },
  {
    name: 'CRO approval',
    sequence: 3,
    thresholdBps: 3000,
    approverRoleKey: 'cro',
    triggersOnNonStandardTerms: false,
    slaHours: 48,
    escalateToRoleKey: 'cfo',
  },
  {
    name: 'CFO approval',
    sequence: 4,
    thresholdBps: 4000,
    approverRoleKey: 'cfo',
    triggersOnNonStandardTerms: false,
    slaHours: 48,
    escalateToRoleKey: null,
  },
  {
    name: 'Deal Desk — non-standard terms',
    sequence: 5,
    thresholdBps: 0,
    approverRoleKey: 'deal_desk',
    triggersOnNonStandardTerms: true,
    slaHours: 12,
    escalateToRoleKey: 'cfo',
  },
] as const;

export const COMPANIES = [
  { name: 'Northwind Logistics', domain: 'northwind.example', industry: 'Manufacturing', region: 'NA', country: 'US', state: 'IL', city: 'Chicago', employees: 8400, tier: 'strategic' },
  { name: 'Helvetica Financial Group', domain: 'helveticafg.example', industry: 'Financial Services', region: 'EMEA', country: 'CH', city: 'Zurich', employees: 14_500, tier: 'strategic' },
  { name: 'Kestrel Health Systems', domain: 'kestrelhealth.example', industry: 'Healthcare', region: 'NA', country: 'US', state: 'MA', city: 'Boston', employees: 22_000, tier: 'strategic' },
  { name: 'Meridian Retail Group', domain: 'meridianretail.example', industry: 'Retail', region: 'EMEA', country: 'GB', city: 'London', employees: 31_000, tier: 'strategic' },
  { name: 'Aurora Telecom', domain: 'auroratelecom.example', industry: 'Telecommunications', region: 'APAC', country: 'AU', city: 'Sydney', employees: 9800, tier: 'enterprise' },
  { name: 'Basalt Energy', domain: 'basaltenergy.example', industry: 'Energy', region: 'NA', country: 'CA', city: 'Calgary', employees: 6200, tier: 'enterprise' },
  { name: 'Corvus Software', domain: 'corvussoftware.example', industry: 'Software', region: 'NA', country: 'US', state: 'CA', city: 'San Francisco', employees: 1850, tier: 'enterprise' },
  { name: 'Dalstrom Industries', domain: 'dalstrom.example', industry: 'Manufacturing', region: 'EMEA', country: 'SE', city: 'Gothenburg', employees: 4100, tier: 'enterprise' },
  { name: 'Everline Insurance', domain: 'everline.example', industry: 'Insurance', region: 'EMEA', country: 'NL', city: 'Amsterdam', employees: 7600, tier: 'enterprise' },
  { name: 'Fernbank Media', domain: 'fernbank.example', industry: 'Media', region: 'NA', country: 'US', state: 'NY', city: 'New York', employees: 2300, tier: 'enterprise' },
  { name: 'Granite Construction Partners', domain: 'graniteconstruct.example', industry: 'Construction', region: 'NA', country: 'US', state: 'TX', city: 'Austin', employees: 3400, tier: 'mid_market' },
  { name: 'Hallow Point Analytics', domain: 'hallowpoint.example', industry: 'Software', region: 'NA', country: 'US', state: 'WA', city: 'Seattle', employees: 620, tier: 'mid_market' },
  { name: 'Ionis Biotech', domain: 'ionisbio.example', industry: 'Healthcare', region: 'EMEA', country: 'DE', city: 'Munich', employees: 980, tier: 'mid_market' },
  { name: 'Juniper Freight', domain: 'juniperfreight.example', industry: 'Transportation', region: 'NA', country: 'US', state: 'GA', city: 'Atlanta', employees: 1450, tier: 'mid_market' },
  { name: 'Kilnwood Foods', domain: 'kilnwood.example', industry: 'Food & Beverage', region: 'EMEA', country: 'IE', city: 'Dublin', employees: 2700, tier: 'mid_market' },
  { name: 'Larkspur Education', domain: 'larkspuredu.example', industry: 'Education', region: 'NA', country: 'US', state: 'CO', city: 'Denver', employees: 890, tier: 'mid_market' },
  { name: 'Maravel Hospitality', domain: 'maravel.example', industry: 'Hospitality', region: 'APAC', country: 'SG', city: 'Singapore', employees: 5100, tier: 'mid_market' },
  { name: 'Nordhaven Marine', domain: 'nordhaven.example', industry: 'Manufacturing', region: 'EMEA', country: 'NO', city: 'Bergen', employees: 1120, tier: 'mid_market' },
  { name: 'Orchid Labs', domain: 'orchidlabs.example', industry: 'Software', region: 'NA', country: 'US', state: 'OR', city: 'Portland', employees: 310, tier: 'smb' },
  { name: 'Pellham Legal', domain: 'pellhamlegal.example', industry: 'Legal', region: 'EMEA', country: 'GB', city: 'Manchester', employees: 240, tier: 'smb' },
  { name: 'Quarrymill Textiles', domain: 'quarrymill.example', industry: 'Manufacturing', region: 'APAC', country: 'IN', city: 'Bengaluru', employees: 1800, tier: 'mid_market' },
  { name: 'Redfern Utilities', domain: 'redfernutil.example', industry: 'Utilities', region: 'APAC', country: 'NZ', city: 'Auckland', employees: 2050, tier: 'mid_market' },
  { name: 'Saltmarsh Property', domain: 'saltmarsh.example', industry: 'Real Estate', region: 'NA', country: 'US', state: 'FL', city: 'Miami', employees: 470, tier: 'smb' },
  { name: 'Tarnhelm Gaming', domain: 'tarnhelm.example', industry: 'Media', region: 'EMEA', country: 'PL', city: 'Warsaw', employees: 690, tier: 'mid_market' },
  { name: 'Umbra Security', domain: 'umbrasec.example', industry: 'Software', region: 'EMEA', country: 'FR', city: 'Paris', employees: 540, tier: 'mid_market' },
  { name: 'Vantage Point Consulting', domain: 'vantagepointco.example', industry: 'Professional Services', region: 'NA', country: 'US', state: 'IL', city: 'Chicago', employees: 1300, tier: 'mid_market' },
  { name: 'Westmere Agriculture', domain: 'westmere.example', industry: 'Agriculture', region: 'APAC', country: 'AU', city: 'Melbourne', employees: 830, tier: 'smb' },
  { name: 'Xander Pharmaceuticals', domain: 'xanderpharma.example', industry: 'Healthcare', region: 'NA', country: 'US', state: 'NJ', city: 'Newark', employees: 11_200, tier: 'enterprise' },
  { name: 'Yarrow Chemicals', domain: 'yarrowchem.example', industry: 'Chemicals', region: 'EMEA', country: 'BE', city: 'Antwerp', employees: 3900, tier: 'mid_market' },
  { name: 'Zenith Aerospace', domain: 'zenithaero.example', industry: 'Aerospace', region: 'NA', country: 'US', state: 'AZ', city: 'Phoenix', employees: 15_600, tier: 'strategic' },
  { name: 'Ashgrove Municipal', domain: 'ashgrove.example', industry: 'Public Sector', region: 'NA', country: 'US', state: 'OH', city: 'Columbus', employees: 4200, tier: 'mid_market' },
  { name: 'Beacon Nonprofit Alliance', domain: 'beaconalliance.example', industry: 'Nonprofit', region: 'NA', country: 'US', state: 'MN', city: 'Minneapolis', employees: 380, tier: 'smb' },
  { name: 'Cindervale Mining', domain: 'cindervale.example', industry: 'Mining', region: 'APAC', country: 'AU', city: 'Perth', employees: 5400, tier: 'enterprise' },
  { name: 'Drayton Automotive', domain: 'drayton.example', industry: 'Automotive', region: 'EMEA', country: 'DE', city: 'Stuttgart', employees: 26_000, tier: 'strategic' },
  { name: 'Elmhurst Bank', domain: 'elmhurstbank.example', industry: 'Financial Services', region: 'NA', country: 'US', state: 'NC', city: 'Charlotte', employees: 9100, tier: 'enterprise' },
  { name: 'Fairholt Apparel', domain: 'fairholt.example', industry: 'Retail', region: 'EMEA', country: 'IT', city: 'Milan', employees: 1600, tier: 'mid_market' },
  { name: 'Glenshire Logistics', domain: 'glenshire.example', industry: 'Transportation', region: 'EMEA', country: 'GB', city: 'Glasgow', employees: 2400, tier: 'mid_market' },
  { name: 'Harborstone Marine Services', domain: 'harborstone.example', industry: 'Transportation', region: 'NA', country: 'US', state: 'WA', city: 'Tacoma', employees: 720, tier: 'smb' },
  { name: 'Inglewood Publishing', domain: 'inglewoodpub.example', industry: 'Media', region: 'NA', country: 'CA', city: 'Toronto', employees: 410, tier: 'smb' },
  { name: 'Jerrow Semiconductors', domain: 'jerrow.example', industry: 'Semiconductors', region: 'APAC', country: 'JP', city: 'Osaka', employees: 18_400, tier: 'strategic' },
] as const;

export const PARTNER_COMPANIES = [
  { name: 'Brightpath Consulting', domain: 'brightpath.example', tier: 'platinum', partnerType: 'si', region: 'NA', country: 'US', marginBps: 3000 },
  { name: 'Continuum Digital', domain: 'continuumdigital.example', tier: 'gold', partnerType: 'reseller', region: 'EMEA', country: 'GB', marginBps: 2500 },
  { name: 'Pacific Rim Distribution', domain: 'pacificrimdist.example', tier: 'distributor', partnerType: 'distributor', region: 'APAC', country: 'SG', marginBps: 3500 },
  { name: 'Salient Advisory', domain: 'salientadvisory.example', tier: 'silver', partnerType: 'referral', region: 'NA', country: 'CA', marginBps: 1500 },
  { name: 'Vertex Managed Services', domain: 'vertexms.example', tier: 'gold', partnerType: 'msp', region: 'EMEA', country: 'DE', marginBps: 2500 },
] as const;

export const FIRST_NAMES = [
  'Alice', 'Marcus', 'Priya', 'Tomas', 'Ingrid', 'Kwame', 'Sofia', 'Daniel', 'Yuki', 'Rachel',
  'Omar', 'Helena', 'Andres', 'Nadia', 'Callum', 'Mei', 'Theo', 'Sinead', 'Ravi', 'Clara',
  'Bjorn', 'Amara', 'Lucas', 'Farida', 'Niamh', 'Hugo', 'Anika', 'Sean', 'Leila', 'Viktor',
  'Rosa', 'Emeka', 'Greta', 'Idris', 'Freya', 'Mateo', 'Zara', 'Owen', 'Lucia', 'Kenji',
];

export const LAST_NAMES = [
  'Whitfield', 'Okonkwo', 'Raman', 'Novak', 'Lindqvist', 'Mensah', 'Duarte', 'Kowalski',
  'Tanaka', 'Brennan', 'Haddad', 'Vasquez', 'Larsen', 'Ferreira', 'MacLeod', 'Chen',
  'Petrov', 'Doherty', 'Iyer', 'Mbeki', 'Halvorsen', 'Achebe', 'Moreau', 'Rasheed',
  'Gallagher', 'Bauer', 'Sharma', 'Kavanagh', 'Nasser', 'Sokolov', 'Alvarez', 'Nwosu',
  'Schneider', 'Farouk', 'Sorensen', 'Delgado', 'Karimi', 'Fitzgerald', 'Rossi', 'Watanabe',
];

export const TITLES_BY_ROLE: Record<string, string[]> = {
  decision_maker: ['Chief Revenue Officer', 'VP Revenue Operations', 'Chief Operating Officer', 'VP Sales'],
  champion: ['Director of Revenue Operations', 'Head of Sales Operations', 'Senior Manager, GTM Systems'],
  administrator: ['CRM Administrator', 'Systems Administrator', 'Platform Owner'],
  user: ['Account Executive', 'Customer Success Manager', 'Renewals Specialist', 'Sales Analyst'],
  procurement: ['Procurement Manager', 'Head of Vendor Management', 'Sourcing Lead'],
  executive_sponsor: ['Chief Financial Officer', 'Chief Executive Officer', 'President'],
  technical_evaluator: ['Enterprise Architect', 'Head of Data Engineering', 'Director of IT'],
  legal: ['General Counsel', 'Commercial Counsel'],
  finance: ['VP Finance', 'Financial Controller', 'Director of FP&A'],
  influencer: ['Business Analyst', 'Programme Manager'],
};

export const LOSS_REASONS = [
  'Lost to incumbent on price',
  'No budget this fiscal year',
  'Chose a competitor on product depth',
  'Project deprioritised',
  'Consolidated onto an existing vendor',
  'Failed security review',
  'Champion left the business',
];

export const CASE_SUBJECTS = [
  'API rate limit reached during nightly sync',
  'Forecast roll-up excluding renewal opportunities',
  'SSO login failing for a subset of users',
  'Territory assignment not applying to new leads',
  'Duplicate contacts created by the marketing sync',
  'Report export timing out beyond 50k rows',
  'Approval notification not reaching the VP',
  'Co-termed amendment showing incorrect proration',
  'Health score confidence unexpectedly low',
  'Sandbox refresh stuck at 40 per cent',
  'Renewal notice date computed a day early',
  'Webhook retries exhausted for the billing connector',
];

export const RISK_TEMPLATES = [
  { type: 'champion_loss', title: 'Champion has moved to a new employer', severity: 'high' },
  { type: 'adoption', title: 'Licence utilisation below 40 per cent', severity: 'medium' },
  { type: 'support', title: 'Repeated severity-1 incidents this quarter', severity: 'high' },
  { type: 'competitive', title: 'Incumbent vendor running a displacement campaign', severity: 'medium' },
  { type: 'budget', title: 'Procurement signalled a budget reduction', severity: 'high' },
  { type: 'consolidation', title: 'Parent company standardising on another platform', severity: 'critical' },
  { type: 'executive_disengagement', title: 'No executive contact in over six months', severity: 'medium' },
];

export const CAMPAIGN_TEMPLATES = [
  { name: 'Revenue Operating System Webinar Series', type: 'webinar', channel: 'digital', budgetCents: 4_500_000, costCents: 4_180_000 },
  { name: 'State of SaaS Retention Report', type: 'content', channel: 'content_syndication', budgetCents: 7_500_000, costCents: 8_120_000 },
  { name: 'SaaStr Annual Field Presence', type: 'event', channel: 'field', budgetCents: 22_000_000, costCents: 24_600_000 },
  { name: 'Renewal Automation Paid Search', type: 'paid_search', channel: 'search', budgetCents: 12_000_000, costCents: 11_400_000 },
  { name: 'RevOps Leaders LinkedIn Programme', type: 'paid_social', channel: 'social', budgetCents: 9_000_000, costCents: 9_650_000 },
  { name: 'Outbound — Enterprise Manufacturing', type: 'outbound', channel: 'outbound', budgetCents: 6_000_000, costCents: 5_800_000 },
  { name: 'Brightpath Co-Marketing Programme', type: 'partner', channel: 'partner', budgetCents: 5_000_000, costCents: 4_900_000, isPartner: true },
  { name: 'Product-Led Trial Nurture', type: 'product_led', channel: 'product', budgetCents: 3_000_000, costCents: 2_750_000 },
  { name: 'Customer Advocacy Referral Programme', type: 'referral', channel: 'referral', budgetCents: 2_000_000, costCents: 1_850_000 },
  { name: 'Executive Roundtables — Financial Services', type: 'field', channel: 'field', budgetCents: 8_500_000, costCents: 8_900_000 },
];

export const INTEGRATION_CATALOGUE = [
  { name: 'Marketo', category: 'marketing_automation', system: 'marketo', direction: 'bidirectional' },
  { name: 'Outreach', category: 'sales_engagement', system: 'outreach', direction: 'bidirectional' },
  { name: 'Gong', category: 'call_intelligence', system: 'gong', direction: 'inbound' },
  { name: 'DocuSign', category: 'e_signature', system: 'docusign', direction: 'bidirectional' },
  { name: 'NetSuite', category: 'erp', system: 'netsuite', direction: 'outbound' },
  { name: 'Zuora', category: 'billing', system: 'zuora', direction: 'bidirectional' },
  { name: 'Stripe', category: 'payments', system: 'stripe', direction: 'inbound' },
  { name: 'Gainsight', category: 'customer_success', system: 'gainsight', direction: 'bidirectional' },
  { name: 'Zendesk', category: 'support', system: 'zendesk', direction: 'bidirectional' },
  { name: 'Product Telemetry Pipeline', category: 'product_telemetry', system: 'segment', direction: 'inbound' },
  { name: 'Okta', category: 'iam', system: 'okta', direction: 'inbound' },
  { name: 'Snowflake', category: 'data_warehouse', system: 'snowflake', direction: 'bidirectional' },
  { name: 'Looker', category: 'bi', system: 'looker', direction: 'outbound' },
  { name: 'Partner Portal', category: 'partner_portal', system: 'spoton_partner_portal', direction: 'bidirectional' },
  { name: 'Slack', category: 'chat', system: 'slack', direction: 'outbound' },
] as const;
